#pragma once

// Editor-only declarations for DisplayManagerNative fragments. Regenerated by:
//   aislop cpp sync-internal DisplayManagerNative

std::string ParseEdidContainerId(const std::vector<BYTE> &edid);
std::string ParseEdidManufactureDate(const std::vector<BYTE> &edid);
std::string ParseEdidSerial(const std::vector<BYTE> &edid);
std::vector<BYTE> ReadEdidFromRegistry(const std::wstring &monitorDevicePath);
std::string WideToUtf8(const std::wstring &wide);
